"""empty message

Revision ID: 6892668b16e7
Revises: 
Create Date: 2022-02-08 19:56:11.591947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6892668b16e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('label', sa.String(length=120), nullable=False))
    op.add_column('todo', sa.Column('done', sa.Boolean(), nullable=True))
    op.drop_constraint('todo_ibfk_1', 'todo', type_='foreignkey')
    op.drop_column('todo', 'todo')
    op.drop_column('todo', 'status')
    op.drop_column('todo', 'user_id')
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.add_column('todo', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('todo', sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('todo', sa.Column('todo', mysql.VARCHAR(length=120), nullable=False))
    op.create_foreign_key('todo_ibfk_1', 'todo', 'user', ['user_id'], ['id'])
    op.drop_column('todo', 'done')
    op.drop_column('todo', 'label')
    # ### end Alembic commands ###
